[global]
pid = /data/data/com.termux/files/home/nginx-portable/php/var/run/php-fpm.pid
error_log = /data/data/com.termux/files/home/nginx-portable/php/var/log/php-fpm.log
log_level = notice
daemonize = no

include=/data/data/com.termux/files/home/nginx-portable/php/etc/www.conf
