#!/data/data/com.termux/files/usr/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH"
exec "$SCRIPT_DIR/bin/php-fpm" -c "$SCRIPT_DIR/etc/php.ini" -y "$SCRIPT_DIR/etc/php-fpm.conf" "$@"
